version: "3.7"

services:
  timescale:
    image: timescale/timescaledb-ha:pg14-latest
    container_name: timescale
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=assetoverflow
      - POSTGRES_PASSWORD=ao071422
      - POSTGRES_DB=aodb
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  web:
    build: .
    command: "./start-aocpp-app.sh"
    volumes:
      - .:/app
    ports:
      - "8000:80"
    depends_on:
      - timescale
    
